name: Automation tests for Gilexpo

on:
  # push:
  #   branches: ["main"]

  pull_request:
    branches: ["main"]

  # schedule:
  #   - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: macos-13

    # strategy:
    #   matrix:
    #     browser: [chrome, firefox]

    steps:
      - name: Checkout Pet project
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          npm ci

      - name: Run succeed test
        run: |
          npm run good_test

  allure:
    name: Generate Allure Report
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Allure results
        uses: actions/download-artifact@v2
        with:
          name: allure-results

      - name: Download Allure report
        uses: actions/download-artifact@v2
        with:
          name: allure-report

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_report: ./allure-report
          allure_results: ./allure-results
          keep_reports: 5
          gh_pages: gh-pages
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      # - name: Allure Report action from marketplace
      #   uses: simple-elf/allure-report-action@master
      #   if: always()
      #   id: allure-report
      #   with:
      #     allure_results: allure-results
      #     gh_pages: gh-pages
      #     allure_report: allure-report
      #     allure_history: allure-history
      #     keep_reports: 5

      # - name: Deploy report to Github Pages
      #   if: always()
      #   uses: peaceiris/actions-gh-pages@v2
      #   env:
      #     PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PUBLISH_BRANCH: gh-pages
      #     PUBLISH_DIR: allure-history

      # - name: Post the link to the report
      #   if: always()
      #   uses: Sibz/github-status-action@v1
      #   with:
      #     authToken: ${{secrets.GITHUB_TOKEN}}
      #     context: "Test report"
      #     state: "success"
      #     sha: ${{ github.event.pull_request.head.sha }}
      #     target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}
