name: Mannually testing and sending report

on:
  workflow_dispatch:
    inputs:
      owner:
        description: "Type your name"
        required: true
        default: "Kristofer"
        type: choice
        options:
          - Artem
          - Edgar
          - Kris

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout Pet project
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          npm ci

      - name: Run succeed test
        run: |
          npm run good_test

      # - name: Check allure report folder
      #   run: |
      #     ls
      #     echo "------------------"
      #     cd allure-report
      #     cd data
      #     ls

      - name: Archive Allure results
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure-results

      - name: Archive Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report

      - name: Download Allure artifacts
        uses: actions/download-artifact@v2
        with:
          name: allure-results

      - name: Create Archives
        run: |
          zip -r allure-results.zip allure-results
          zip -r allure-report.zip allure-report
          echo `${{ github.workspace }}`
          echo `$GITHUB_WORKSPACE`

      - name: Send email
        uses: devellany/send-mail@v1.0.2
        with:
          host: "smtp.mail.ru"
          account: ${{secrets.USER_EMAIL}}
          password: ${{secrets.USER_PASSWORD}}
          sender: "KG"
          from: ${{secrets.USER_EMAIL}}
          subject: Github Actions job result
          body: "report"
          attachments: '[{"path":"allure-results.zip"},{"path":"allure-report.zip"}]'
          to: ${{secrets.USER_EMAIL}}
